### ISSUE TITLE
Broken recovery with wrong trusted connections

### ISSUE THREAD

**Issue by alirezapaslar** [BrightID/BrightID#576] opened 2020-10-20 23:26 UTC
The app lets the user recover with wrong trusted connections. It'll show the picture, name, and connections. But the user won't be able to make new connections to people who are not already connected with him/her. And they cannot register to or use apps.

**Comment by TripleSpeeder** [comment] 2021-03-19 10:32
Since this issue was reported there were many changes to the recovery process. I could not reproduce this in any way. Closing.

**Closed by TripleSpeeder** 2021-03-19 10:32 UTC
Labels: bug, recovery
