### ISSUE TITLE
Onboarding Text box to enter name is partially hidden

### ISSUE THREAD

**Issue by theobtl** [BrightID/BrightID#237] opened 2019-01-29 09:12 UTC
During sign-up, the text box to enter a name is partly hidden. See the upper part of the "T" here: https://photos.app.goo.gl/GbBXfJKMUMZ1H9GN8

Device info: OnePlus 5, Android 9

**Comment by theobtl** [comment] 2019-01-29 09:14
That said, kudos to the team, idea and implementation are super exciting!

**Comment by adamstallard** [comment] 2019-06-05 23:42
Duplicate of #230

**Comment by adamstallard** [comment] 2019-08-09 08:14
Might still be a bug  Also not a dupe of #230 , this is about the top of the font being obscured.  Maybe it's too big for the text box somehow.

**Comment by adamstallard** [comment] 2019-11-26 18:47
Closing in favor of #230

**Closed by adamstallard** 2019-11-26 18:47 UTC
Labels: good first issue, priority 1
