### ISSUE TITLE
Strange error message about profile when connecting

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#759] opened 2021-03-08 07:45 UTC
The connection succeeded, but this error was shown.

![Screenshot_2021-03-05-21-02-45-121_org.brightid.jpg](https://user-images.githubusercontent.com/205792/110289939-f8c2ac00-7f9e-11eb-9f43-2a277d41946c.jpg)

**Comment by TripleSpeeder** [comment] 2021-03-08 09:27
This looks like the upload of the channelinfo.json file failed. Was this in any way reproducible?

**Comment by TripleSpeeder** [comment] 2021-03-25 08:29
I can think of 2 possible reasons for this error:
- The profile server restarted after the channel was created. Since uploaded data is only kept in memory the ChannelInfo.json file would be lost in this scenario.
- There was a network problem on the device creating the channel, so the upload of the ChannelInfo.json failed.

These are both edge cases that should happen very rarely. Closing this for now, will re-open if we get this error reported again.

**Closed by TripleSpeeder** 2021-03-25 08:29 UTC
Labels: bug
